# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQ1lnBTCfq42tdLruzCCA3y40-Acx9ah
"""



# TF-IDF Keyword Extraction and Visualization

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

# ---------------------------------------------------
# 1. Input documents
# ---------------------------------------------------

documents = [
    """
    Machine learning is a branch of artificial intelligence.
    Machine learning algorithms learn patterns from data.
    """

    ,

    """
    Deep learning is a subfield of machine learning.
    Deep learning uses neural networks to learn complex patterns.
    """

    ,

    """
    Natural language processing allows computers to understand
    and process human language using machine learning techniques.
    """
]

# ---------------------------------------------------
# 2. Create TF-IDF Vectorizer
# ---------------------------------------------------

vectorizer = TfidfVectorizer(
    stop_words='english',
    lowercase=True
)

tfidf_matrix = vectorizer.fit_transform(documents)

# Get all words/features
feature_names = vectorizer.get_feature_names_out()

# ---------------------------------------------------
# 3. Calculate average TF-IDF score for each word
# ---------------------------------------------------

average_scores = tfidf_matrix.mean(axis=0).A1

# Create dictionary of words and scores
tfidf_scores = dict(zip(feature_names, average_scores))

# Sort words according to TF-IDF score
sorted_keywords = sorted(
    tfidf_scores.items(),
    key=lambda x: x[1],
    reverse=True
)

# ---------------------------------------------------
# 4. Display all TF-IDF scores
# ---------------------------------------------------

print("TF-IDF Scores:")
print("-" * 40)

for word, score in sorted_keywords:
    print(f"{word:20s} {score:.4f}")

# ---------------------------------------------------
# 5. Identify Top Keywords
# ---------------------------------------------------

top_n = 10

top_keywords = sorted_keywords[:top_n]

print("\nTop Keywords:")
print("-" * 40)

for word, score in top_keywords:
    print(f"{word:20s} {score:.4f}")

# ---------------------------------------------------
# 6. Visualization
# ---------------------------------------------------

words = [item[0] for item in top_keywords]
scores = [item[1] for item in top_keywords]

plt.figure(figsize=(10, 6))

plt.bar(words, scores)

plt.xlabel("Keywords")
plt.ylabel("Average TF-IDF Score")
plt.title("Top Keywords Based on TF-IDF")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()